# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(536, 507)
        ChatWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 11pt \"FreeMono\";")
        self.centralwidget = QtWidgets.QWidget(ChatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_history = QtWidgets.QTextBrowser(self.centralwidget)
        self.chat_history.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(78, 154, 6);\n"
"font: 14pt \"FreeMono\";")
        self.chat_history.setObjectName("chat_history")
        self.verticalLayout.addWidget(self.chat_history)
        self.message_input = QtWidgets.QLineEdit(self.centralwidget)
        self.message_input.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(0, 0, 0);")
        self.message_input.setText("")
        self.message_input.setObjectName("message_input")
        self.verticalLayout.addWidget(self.message_input)
        self.sendmessage_button = QtWidgets.QPushButton(self.centralwidget)
        self.sendmessage_button.setStyleSheet("color: rgb(78, 154, 6);\n"
"font: 13pt \"FreeMono\";")
        self.sendmessage_button.setObjectName("sendmessage_button")
        self.verticalLayout.addWidget(self.sendmessage_button)
        ChatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 20))
        self.menubar.setObjectName("menubar")
        ChatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChatWindow)
        self.statusbar.setObjectName("statusbar")
        ChatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "MainWindow"))
        self.chat_history.setHtml(_translate("ChatWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'FreeMono\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.sendmessage_button.setText(_translate("ChatWindow", "Enviar mensagem"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatWindow = QtWidgets.QMainWindow()
    ui = Ui_ChatWindow()
    ui.setupUi(ChatWindow)
    ChatWindow.show()
    sys.exit(app.exec_())
